version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
